# -- #
# Discord Region

# Discord Bot Token
bot_token: ""
# Discord Bot Prefix
bot_prefix: "!"
# Discord Bot Owner ID
bot_owner_id: ""
# Discord Bot Allowed usage role ID
bot_allowed_role: ""
# Max number of simultaneously connected users (default: 3):
max_chats: ""

# -- #
# End Discord Region

# -- #
# OpenAI Region

# OpenAI API Key
openai_key: ""
# AI Engine (default: "text-davinci-003")
ai_engine: ""
# AI Temperature (0-1) (Default: 0.7)
temperature: ""

# -- #
# End OpenAI Region

# -- #
# Start Database Region

# Database host:
db_host: ""
# Database Name:
db_name: ""
# Database User:
db_user: ""
# Database Pass:
db_pass: ""

# -- #
# End Database Region